# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: unicode
  database: conti2-dev
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: conti2-test
  pool: 5


production:
  adapter: postgresql
  encoding: unicode
  database: conti2-prod
  pool: 5
